### PR TITLE
Applying Trait's definitions to the resources during postProcess

### PR DESCRIPTION
**Pull request by fstaoe**
Hi,

First of all, I would like to thank you for all the work which has been done in this project and by sharing it.

I am using it and I would like to contribute with something I found useful to be clarified/fixed, so it comes:

The collections declared as Libraries are not being loaded to the root of the API definition. This PR is about loading the collections declared as Libraries adding it to the root of the APIDefinition.

These changes allow the parser to work properly (in my understanding :)) when doing the inheritance from Traits in the raml.Method context. it was not considering the Traits declared as Library.

e.g. the raml.Resource has the postProcess method that is receiving the apiDef.Traits that will be inherited by the raml.Method definition in the inheritFromTraits method but the apiDef.Traits doesn't contain the Traits declared as Library.

### CODE REVIEW

**Comment by iwanbk** [comment]
@fstaoe 
thank you very much for this PR. 
I'll definitely check again how the libraries being parsed.

Can you help me reviewing your PR by fixing the travis build of this PR?

It currently failed
```
time="2017-02-23T16:57:33Z" level=error msg="Error running go fmt on '/tmp/504405295/file-type.File.go' failed:\n/tmp/504405295/file-type.File.go:9:10: expected type, found '-'\n/tmp/504405295/file-type.File.go:16:18: expected 'IDENT', found '.'\n" 
✘
Failures:
  * /home/travis/gopath/src/github.com/Jumpscale/go-raml/codegen/golang/libraries_test.go 
  Line 65:
  Expected: nil
  Actual:   'go fmt failed'
```

**Comment by fstaoe** [comment]
@iwanbk I have a question. What would you expect from the merge between Types existing in the root level and the Types existing in a Library? Would you expect to have the Types coming from the library prefixed with the library's namespace (e.g. typesLib.Custom) or not prefixed (e.g. Custom)? 

Please consider the following example:

#Example API definition
#api.raml
`#%RAML 1.0
title: Your API
version: 1
uses:
   typesLib: libraries/types.raml
types:
  Custom:
    type: string`

#libraries/types.raml
`#%RAML 1.0 Library
types:
  Custom:
    type: array
    description: "A custom array type"`

#After the merge
#result from go-raml/raml/parser.ParseFile method
'&raml.APIDefinition{
    RAMLVersion:  "",
    Title:                 "Your API",
    Version:           "1",
    Types: {
       "Custom": {
          Type: "string",
          ...
       },
       "typesLib.Custom": {
          Type: "array",
          Description: "A custom array type",
          ...
       },
    },
}'

The approach of having the library's namespace in the Type's name after merging allow us to avoid naming collisions, otherwise, we have to decide if we give an error when a collision occurs or if we overwrite the existing Type.

Please let me know what are you thoughts about this topic. Meanwhile I will fix the tests and also write one to ensure this logic.

**Comment by iwanbk** [comment]
@fstaoe 
Sorry for late response.
i prefer it to be not prefixed because the `type` declared in the lib will not exist in root APIDefinition, it only exist in Library's type. It also already provide namespacing.

**Comment by fstaoe** [comment]
@iwanbk Hey, no problem. Thank you for your availability.

I've just finished the "fix" and it is ready to be reviewed.

I've reduced the scope a bit applying the same behaviour for Traits as it's being applied for ResourceTypes. I've created a test to ensure the traits are being merged with the resource's definition.

I have another question, should the SecuritySchemes definitions (such as headers) not be merged as the Traits do?

e.g OAuth 2.0 - I've the header Authorization defined, should the header not be merged with the headers of the resource/method using this scheme on securedBy?

**Comment by iwanbk** [comment]
thanks @fstaoe

**Pull request merged**
