### PR TITLE
Raml1.0 rc2

### LINKED ISSUE #77: new map syntax support
Map syntax has been changed in latest RAML specs

### PR DESCRIPTION
**Pull request by iwanbk**
fix #77 & #80 
Improve parser to support raml1.0-rc2

### CODE REVIEW

**Comment by robvanmieghem** [comment]
Isn't the "map" type still supported by the `//: ` syntax?

**Comment by iwanbk** [comment]
@robvanmieghem 
I also have asked about this yesterday on that GH issue and i think the conclusion is there is no Map type.
See last answer https://github.com/raml-org/raml-spec/issues/286#issuecomment-216485537 by  sichvoge yesterday

**Comment by robvanmieghem** [comment]
I saw your question and the answer from sighvoge but I think there is some misunderstanding. I do think your example in that question defines a string "map" type even though the map type as such does not exist anymore. Additionalproperties are now defined with the '//:' syntax and the simple map declaration does not exist anymore (too bad, liked that one).

**Comment by iwanbk** [comment]
@robvanmieghem 
I don't get your point.
So, how we define a Map now? for example map with key = string and value=int or `map[string]int` in Go

**Comment by robvanmieghem** [comment]
@iwanbk your example
```
types:
  mapOfInt:
    properties:
      //: int
```
defines a map of string. What is annoying is how we are going to do this in the case of 
```
types:
  mixedMap:
    properties:
      label: string
      //: int
```

**Comment by iwanbk** [comment]
```
types:
  mapOfInt:
    properties:
      //: int
```
Ahh..thanks

In `mixedMap` case, it is not a map because there is non pattern properties.

**Comment by iwanbk** [comment]
`In mixedMap case, it is not a map because there is non pattern properties.`
Rules to decided that a type is a map:
- have only one property, and it is a pattern property
- additionalProperties = true

**Comment by robvanmieghem** [comment]
@iwanbk I think this is correct

**Comment by iwanbk** [comment]
But if we specify `additionalProperties=true`, then in case of `mapOfInt`.
This JSON is valid
```
{
    "a": 1,
    "b": 2
}
```
but this also valid
```
{
    "a": 1,
    "b": 2,
    "name": "google"  -> additional properties.
}
```
see https://github.com/raml-org/raml-spec/issues/286#issuecomment-216772757

So, it seems that Map is indeed not exist

**Comment by iwanbk** [comment]
I have checked JSON data types in 
https://en.wikipedia.org/wiki/JSON#Data_types.2C_syntax_and_example.

There is indeed no Map there.

We actually can't differentiate between Map & Object in JSON.
(As a side note, mongodb  also doesn't support Map type).

I think we can still support Map by using user-defined facets https://github.com/raml-org/raml-spec/blob/raml-10-rc2/versions/raml-10/raml-10.md#user-defined-facets, put an instruction that user want to generate a map.

**Comment by robvanmieghem** [comment]
@iwanbk I am closing the pull request for now but leaving the branch. Tool support for rc2 is not widely spread yet so I think it is better to wait a bit before merging it in to the master branch.

**Pull request closed without merging**
