### PR TITLE
Handle multiple inflectors on a raml resource

### PR DESCRIPTION
**Pull request by jasco**

### CODE REVIEW

**Comment by iwanbk** [comment]
thanks @jasco.
is it possible to add test case for this patch?

**Comment by jasco** [comment]
@iwanbk, I added a multi inflector/transformer case to the test sample.  I also added support for whitespace padding around the separator.

**Comment by jasco** [comment]
@iwanbk Just added space-> tab whitespace fix.

**Comment by iwanbk** [comment]
thanks @jasco 
```
Just added space-> tab whitespace fix.
```
you might want to integrate `go fmt` to your editor

**Pull request merged**
