### PR TITLE
python and java clients

### PR DESCRIPTION
**Pull request by razor-1**
ref #210 plus do the same for Java with jackson and gson annotations

### CODE REVIEW

**Comment by iwanbk** [comment]
@razor-1 thanks for the PR.

The PR is much bigger than expected :-)

for java client, it is likely be accepted, but marked as `experimental` because we still need to test it and add some unit tests.

for python client, i can see at least 4 changes:
- class
- main client
- services
- setup.py

`class` & `setup.py` is likely be accepted, while the other is not now because we have `aiohttp` client now :).
Your `main client` and `services` related code will not be deleted because i can see some improvements there.

Let me know if you can do the needed changes.
If not, i will try to rebase your PR to current master and make needed changes.

**Comment by razor-1** [comment]
Hi @iwanbk if you can do the changes to main client and services it would be better I think, and more timely. I will try to review if you want.

**Comment by iwanbk** [comment]
Hi @razor-1 
i just found that your PR touch more files than expected.
I'm afraid i need to only pick the parts i like and left the other, this way, you'll loose your commit history and i'll take credit for your work.

I think you can easily avoid this for java client,  by sending another PR that only contains java client.

for python client, i can give you credit in readme or somewhere.

Let me know what you think.

**Comment by razor-1** [comment]
Sure, no problem, that sounds good

**Comment by iwanbk** [comment]
I have extracted the python class support code from this PR, fixed some bugs, and add RAML multiple inheritance support ( the `[ T1, T1]` notation).

Test fixtures can be found in https://github.com/Jumpscale/go-raml/tree/python-class/codegen/python/fixtures/class dir.

next step is looking for a way for the python classes to be more integrated with python client.

**Comment by iwanbk** [comment]
@razor-1 
python class implementation has been merged to master.
we are still waiting for your java client PR :)

Thanks

**Comment by razor-1** [comment]
Thanks I will close this an open a new one for Java

**Comment by iwanbk** [comment]
great!

I will also add setup.py based on this PR.

**Pull request closed without merging**
