### PR TITLE
Use new arg format for cli.

### PR DESCRIPTION
**Pull request by calebcase**
Issue #90

### CODE REVIEW

**Comment by iwanbk** [comment]
Thanks @calebcase 

we don't need to change old style code
```
if err := serverCommand.Execute(); err != nil {
                    log.Error(err)
                }
```
to
```
err := serverCommand.Execute();
if err != nil {
     log.Error(err) 
}
```
But overall it looks good for me.

**Comment by iwanbk** [comment]
@calebcase 
it seems you need to update codegangsta/cli dependency in Godep as well.
```
#godep go test ./...
godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
# github.com/Jumpscale/go-raml
./main.go:94: cannot use func literal (type func(*cli.Context) error) as type func(*cli.Context) in field value
./main.go:126: cannot use func literal (type func(*cli.Context) error) as type func(*cli.Context) in field value
./main.go:134: cannot use func literal (type func(*cli.Context) error) as type func(*cli.Context) in field value
./main.go:141: cannot use func literal (type func(*cli.Context) error) as type func(*cli.Context) in assignment
```

Travis didn't catch it because it seems travis doesn't use godep.
https://travis-ci.org/Jumpscale/go-raml/builds/128361433
```
Using Go 1.5 Vendoring, not checking for Godeps
```

**Comment by calebcase** [comment]
@iwanbk Would it be acceptable switch from godep to using a vendor directory with submodules?

**Comment by iwanbk** [comment]
@calebcase 
We have a plan to  use Go 1.6 vendoring without git submodules.
We will do it after fixing another issue (#92)

For now, we need to stick with godep.
These are what you need to do to update dependency:
- rebase from master
- `godep update github.com/codegangsta/cli`

**Comment by iwanbk** [comment]
@calebcase 
Can you update the PR? I will fix it if you don't have time to do it.

**Comment by calebcase** [comment]
@iwanbk Unfortunately keeping the style with the if statements doesn't work because the scope of err is wrong (only scoped to within the if itself).

**Comment by calebcase** [comment]
I've tried a couple of times to get godep to update codegangsta/cli, but it always reports:
```
/go/src/github.com/Jumpscale/go-raml# godep update github.com/codegangsta/cli
godep: no packages can be updated
```

**Comment by calebcase** [comment]
Actually, since this is pinned in recent master this problem doesn't occur anymore. I'm dropping this PR.

**Pull request closed without merging**
