### PR TITLE
Support JSON omitempty

### PR DESCRIPTION
**Pull request by ygmpkk**
1. Support JSON omitempty parameter
2. Solve Boolean value caused by the default value of required are false

Example:

```
Test:
    type: object
    properties:
      title: string # required = true
      description?: # required = false
        type: string
      classify:
        type: TemplateClassify
      schema:
        type: TemplateSchema
```

### CODE REVIEW

**Comment by robvanmieghem** [comment]
LGTM

**Comment by iwanbk** [comment]
@ygmpkk thanks for this PR!

I think `required` is not about API response but it is about API request.
So it should be implemented as part of validator which validates the inputs, not `omitempty` which affect response's behaviour.
CMIIW.

**Comment by robvanmieghem** [comment]
@iwanbk even though your are absolutely right about the request part and the validators, I do think `omitempty` is nice to have for the response, it certainly does not harm, on the contrary, is more in line with the how the raml spec defines required.

**Comment by iwanbk** [comment]
you're right @robvanmieghem

**Comment by robvanmieghem** [comment]
@ygmpkk thanks!

**Pull request merged**
