### PR TITLE
Python client unmarshal resp

### LINKED ISSUE #318: Returns actual type instead of http response
Currently when generating a python client, the methods return `response` object on which we need to execute `content` or `json` or other method like that.

I would be nice if instead of returning a `response` object the method returns an object of the type that the method actually returns.
For example a method  that would return a json body like this:
```json
{
   "id": "myid",
   "data": "hello world"
}
```
Would return a object with the `id` and `data` property. In case of failure, an exception that contain the http response would be raise, so we can still inspect it.

Go-raml already support the generation of these types, so I don't think that would be a lot of work to implement this feature.

### PR DESCRIPTION
**Pull request by iwanbk**
Closes #318 

notable generated files:
- exception class: https://github.com/Jumpscale/go-raml/blob/python-client-unmarshal-resp/codegen/python/fixtures/client/requests_client/unmarshall_response/unmarshall_error.py

- requests client : https://github.com/Jumpscale/go-raml/blob/python-client-unmarshal-resp/codegen/python/fixtures/client/requests_client/unmarshall_response/users_service.py

- aiohttp client : https://github.com/Jumpscale/go-raml/blob/python-client-unmarshal-resp/codegen/python/fixtures/client/aiohttp_client/unmarshall_response/users_service.py

### CODE REVIEW

**Comment by zaibon** [comment]
I like that. Only concerne I we don't have access to the response object anymore when the requests succeed. Not sure it's acceptable. On most case I guess people will not care cause they already define the correct status code of the request they expect.
But sometime I guess people want to inspect a bit more. Like the headers for example.

**Comment by iwanbk** [comment]
> I like that. Only concerne I we don't have access to the response object anymore when the requests succeed. Not sure it's acceptable. On most case I guess people will not care cause they already define the correct status code of the request they expect.

I can only think that we can return two values: 
- response object
- the python class

Not sure if it is pythonic

**Comment by iwanbk** [comment]
> I can only think that we can return two values:

The other option is to return `dictionaries`

```python
return {'response': resp, 'data': data}
```

With this, we don't need to add wrapper or extend the response object.

**Comment by iwanbk** [comment]
> The other option is to return dictionaries

I updated the generated code to use named tuple, with:
`response` and `data` field

**Pull request merged**
